# Generated by Django 5.1.2 on 2024-11-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='Categoria',
            new_name='Categoria_id',
        ),
    ]
