# Generated by Django 5.1.2 on 2024-11-18 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='Telefono',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.empresa'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
