# Generated by Django 5.1.2 on 2024-12-08 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clientes_promociones_precio_total_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
