# Generated by Django 5.1.2 on 2024-11-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_categoria_id_productos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='promociones',
            name='Precio_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
