# Generated by Django 5.1.2 on 2024-12-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Imagen_Producto',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
