# Generated by Django 5.1.2 on 2024-12-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_promociones_precio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='promociones',
            name='url_imagen',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
