# Generated by Django 5.1.2 on 2024-12-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ventas_id_producto_alter_ventas_id_promociones'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='Comprobante',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
