# Generated by Django 5.1.2 on 2024-12-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ventas_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='Ventas_asociadas',
            field=models.ManyToManyField(to='api.ventas'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='Total_ventas',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
