# Generated by Django 5.1.2 on 2024-12-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reporte_ventas_asociadas_alter_reporte_total_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='empresa',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Direccion_envio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Foto_perfil',
            field=models.URLField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Numero_telefono',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
